# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-04 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=255)),
                ('client_logo', models.ImageField(upload_to='clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=50)),
                ('phone_timing', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('google', models.CharField(max_length=255)),
                ('pintrest', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('main_body_image', models.ImageField(upload_to='main_body_image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=255)),
                ('salutation', models.CharField(choices=[('NONE', 'None'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('DR', 'Dr'), ('PROF', 'Prof')], max_length=4)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(choices=[('NONE', 'None'), ('GENERAL RETAIL GOODS/SERVICES', 'General Retail Goods/Services'), ('FITNESS CENTER/GYM', 'Fitness Centre/Gym'), ('BEAUTY, HAIR AND SLIMING', 'Beauty, Hair and Slimming'), ('MOTO AND ECOMMERCE', 'MOTO and eCommerce'), ('EDUCATION', 'Education'), ('MLM/DIRECT SELLING', 'MLM/Direct Selling'), ('ALOCHOL/TOBACCO', 'Alcohol/Tobacco'), ('TRADING/FOREX', 'Trading/Forex'), ('RESTURANT/CAFE', 'Restaurant/Cafe'), ('BILL PAYMENT/MOBILE TOPUP', 'Bill Payment/Mobile Topup'), ('HANDPHONE SHOP/REPAIR', 'Handphone Shop/Repair'), ('RETAIL (SHOPPING MALL TENANT)', 'Retail (Shopping Mall Tenant)'), ('CLINIC/HEALTHCARE', 'Clinic/Healthcare'), ('TRANSPORTATION/CAR RENTAL', 'Transportation/Car Rental'), ('BAR/NIGHTCLUB', 'Bar/Nightclub')], max_length=255)),
                ('salay', models.IntegerField()),
                ('description', models.TextField()),
                ('bank', models.CharField(choices=[('ALLIANCE BANK', 'Alliance Bank'), ('AMBANK', 'AmBank'), ('BANK ISLAM', 'Bank Islam'), ('BANK MUAMALAT', 'Bank Muamalat'), ('BSN', 'BSN'), ('CIMB', 'CIMB'), ('CITIBANK', 'CitiBank'), ('GLOBAL PAYMENTS', 'Global Pyaments'), ('HONG LEONG', 'Hong Leong'), ('MAYBANK', 'MayBank'), ('OCBC', 'OCBC'), ('PUBLIC BANK', 'Public Bank'), ('RHB', 'RHB'), ('STANDARD CHARTERED', 'Standard Chartered'), ('SYNERGY', 'Synergy'), ('UOB', 'UOB')], max_length=50)),
                ('lead_source', models.CharField(choices=[('PHONE', 'Phone'), ('SEARCH ENGINE', 'Search Engine'), ('WORD OF MOUTH', 'Word Of MoUth'), ('EMPLOYEE REFERRAL', 'Employee Referral'), ('OTHER', 'Other')], max_length=100)),
                ('contact_method', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('APPOITMENT', 'Appointment')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('desc_image', models.ImageField(upload_to='services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('slider_image', models.ImageField(upload_to='slider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('team_profile', models.ImageField(upload_to='team_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('testimony_profile_image', models.ImageField(upload_to='testimony_profile_image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
