# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-06 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
