# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-07 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testimony_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 7, 5, 36, 48, 706505, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
