# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170407_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='mobile',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
