# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170415_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='land_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
